version: '3.8'

services:
  wp:
    container_name: wp-docker
    build:
      context: ./wp
      dockerfile: ../config/Dockerfile
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp:/var/www/html
    depends_on:
      - db
    environment:
      DB_NAME: wordpress
      DB_USER: root
      DB_PASSWORD: 123456
      DB_HOST: db
      DB_PREFIX: wp_
      WP_ADMIN: admin
      WP_ADMIN_EMAIL: admin@example.com
      WP_ADMIN_PASSWORD: qwerty123
      WP_TITLE: WP Site on Docker
      LIVE_URL: 127.0.0.1:80
      DEV_URL: 127.0.0.1:80
    networks:
      - wp-network

  db:
    container_name: mysql-docker
    image: mysql:8.0.33
    ports:
       - "127.0.0.1:3307:3307"
    volumes:
      - db:/var/lib/mysql
      - ./db_dumps:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: wordpress
    command: [
      '--default_authentication_plugin=mysql_native_password',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--skip-host-cache',
    ]
    networks:
      - wp-network


networks:
  wp-network:

volumes: 
    db:
